export enum RequestErrorCodes {
    MISSING_PARAMETER = "MISSING_PARAMETER",
    MISSING_QUERY_PARAMETER = "MISSING_QUERY_PARAMETER",
    MISSING_PROPERTY = "MISSING_PROPERTY",
    INVALID_PARAMETER_TYPE = "INVALID_PARAMETER_TYPE",
    INVALID_QUERY_PARAMETER_TYPE = "INVALID_QUERY_PARAMETER_TYPE",
    INVALID_PROPERTY_TYPE = "INVALID_PROPERTY_TYPE",
    DATABASE_ERROR = "DATABASE_ERROR"
}

export enum AuthenticationErrorCodes{
    EMPTY_EMAIL_PROPERTY = "EMPTY_EMAIL_PROPERTY",
    EMPTY_PASSWORD_PROPERTY = "EMPTY_PASSWORD_PROPERTY"
}

export enum TodoErrorCodes{
    EMPTY_TITLE_PROPERTY = "EMPTY_TITLE_PROPERTY",
    EMPTY_DESCRIPTION_PROPERTY = "EMPTY_DESCRIPTION_PROPERTY",
}